### ISSUE TITLE
Update Licensing

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/terraform-provider-nautobot#4]
Look to migrate to Apache licensing if we will be allowed to do so.

**Comment by jvanderaa** [comment]
Need to work with any previous contributors to the project to make that license migration.

**Comment by chadell** [comment]
Yes, I think we change the license as needed. @nleiva , the original author, supports it.

**Comment by nleiva** [comment]
Yep, I'm OK with it.

**Comment by chadell** [comment]
done with #5
